id: PC1317B16
initial_creation_type: ocr
source_metadata:
  volumes:
    32291c1be1c3411d99ce37171ed6ca22:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: ལག་པའི་ཚད་ཀྱི་འགྲེལ་པ།
      total_pages: 1605
      volume_number: 57
